HRM/HRM.MVC/Controllers/DepartmentController.cs
using Application.CQRS.Commands.Departments;
using Application.CQRS.Queries.Departments;
using Application.CQRS.Queries.Positions;
using Application.DTOs;
using Domain.Entities;
using Microsoft.AspNetCore.Mvc;
using MediatR;

namespace HRM.MVC.Controllers;

public class DepartmentController : Controller
{
    private readonly IMediator _mediator;

    public DepartmentController(IMediator mediator)
    {
        _mediator = mediator;
    }
    
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var query = new GetAllDepartmentsQuery();
        var departments = await _mediator.Send(query);
        var positionsQuery = new GetAllPositionsQuery();
        await _mediator.Send(positionsQuery);
        return View(departments.ToList());
    }
    
    [HttpGet]
    public IActionResult Add()
    {
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> Add(string name)
    {
        if (!ModelState.IsValid) return RedirectToAction("Add");
        var departmentDto = new DepartmentDto(name);
        var command = new CreateDepartmentCommand(departmentDto);
        await _mediator.Send(command);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> GetById(int departmentId)
    {
        var query = new GetDepartmentByIdQuery(departmentId);
        var response = await _mediator.Send(query);
        return View(response);
    }
    
    [HttpGet]
    public async Task<IActionResult> Delete(int departmentId)
    {
        var command = new DeleteDepartmentCommand(departmentId);
        await _mediator.Send(command);
        return RedirectToAction("Index");
    }
    
    [HttpGet]
    public async Task<IActionResult> Edit(int departmentId)
    {
        var query = new GetDepartmentByIdQuery(departmentId);
        var department = await _mediator.Send(query);
        return View(department);
    }
    
    [HttpPost]
    public async Task<IActionResult> Update(IFormCollection collection)
    {
        var departmentId = int.Parse(collection["Id"]!);
        var name = collection["Name"];
        var departmentDto = new DepartmentDto(name!);
        var command = new UpdateDepartmentCommand(departmentDto, departmentId);
        await _mediator.Send(command);
        return RedirectToAction("Index");
    }
}

HRM/HRM.MVC/Views/Department/Add.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Domain.Entities.Department

@{
    ViewBag.Title = "Add";
    Layout = "_Layout";
}

<h2>Form to add a new department</h2>
<div class="row">
    <div class="col-md-6">
        <form asp-action="Add" method="post">
            <div class="form_row">
                <label for="">
                    Name
                    <input asp-for="Name" type="text">
                </label>
                <span asp-validation-for="Name"></span>
            </div>
            <button type="submit">Add</button>
        </form>
    </div>
</div>

HRM/HRM.MVC/Views/Department/Edit.cshtml
@model Domain.Entities.Department

@{
    ViewBag.Title = "Edit";
    Layout = "_Layout";
}

<h2>Form to edit department</h2>

@using (Html.BeginForm("Update", "Department", FormMethod.Post))
{
    <fieldset>
        <p><b>Associate Id : </b>@Model.Id</p>
        @Html.HiddenFor(m => m.Id)
        <p>
            @Html.LabelFor(m => m.Name, "Name")
            <br/>
            @Html.EditorFor(m => m.Name)
        </p>
        <p><input type="submit" value="Edit"/></p>
    </fieldset>
}

HRM/HRM.MVC/Views/Department/GetById.cshtml
@model Domain.Entities.Department

@{
    ViewBag.Title = "Department info";
    Layout = "_Layout";
}

<h1>@Model.Name</h1>

<div class="table_section">
    <table style="width: 100%;">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Stuff count</th>
        </tr>
        <tr>
            <td>@Model.Id</td>
            <td>@Model.Name</td>
            <td>@Model.Positions.Count</td>
        </tr>
    </table>
</div>

HRM/HRM.MVC/Views/Department/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model List<Domain.Entities.Department>
@{
    ViewBag.Title = "Departments";
    Layout = "_Layout";
}

<h2>Company departments</h2>
<a asp-action="Add" asp-controller="Department">Add department</a>
<div class="table_section">
    @if (@Model.Count == 0)
    {
        <p>There is no any departments yet.</p>
    }
    else
    {
        <table style="width: 100%;">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Positions count</th>
            </tr>
            @foreach (var department in @Model)
            {
                <tr>
                    <td>@department.Id</td>
                    <td>@department.Name</td>
                    <td>@department.Positions.Count</td>
                    <td>
                        <a asp-action="GetById" asp-controller="Department" asp-route-departmentId="@department.Id">View</a>
                        </td>
                    <td>
                        <a asp-action="Delete" asp-controller="Department" asp-route-departmentId="@department.Id">Delete</a>
                    </td>
                    <td>
                        <a asp-action="Edit" asp-controller="Department" asp-route-departmentId="@department.Id">Edit</a>
                    </td>
                </tr>
            }
        </table>
    }
</div>