HRM/HRM.MVC/Controllers/PositionController.cs
using Application.CQRS.Commands.Positions;
using Application.CQRS.Queries.Departments;
using Application.CQRS.Queries.Positions;
using Application.DTOs;
using Domain.Entities;
using HRM.MVC.ViewModels;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HRM.MVC.Controllers;

public class PositionController : Controller
{
    private readonly IMediator _mediator;

    public PositionController(IMediator mediator)
    {
        _mediator = mediator;
    }
    
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var query = new GetAllPositionsQuery();
        var positions = await _mediator.Send(query);
        var departmentQuery = new GetAllDepartmentsQuery();
        await _mediator.Send(departmentQuery);
        return View(positions.ToList());
    }
    
    [HttpGet]
    public async Task<IActionResult> Add()
    {
        var query = new GetAllDepartmentsQuery();
        var departments = await _mediator.Send(query);
        ViewBag.departments = new SelectList(departments, "Name", "Name");
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> Add(AddPositionViewModel model)
    {
        if (!ModelState.IsValid) return RedirectToAction("Add");
        var departments = await _mediator.Send(new GetAllDepartmentsQuery()) as List<Department>;
        if (departments is null) throw new Exception("Company doesn't have such department!");
        var department = departments.SingleOrDefault(d => d.Name == model.DepartmentName);
        if (department is null) throw new Exception("Such department doesn't exist!");
        var positionDto = new PositionDto(model.Name, department.Id);
        var command = new CreatePositionCommand(positionDto);
        await _mediator.Send(command);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> GetById(int positionId)
    {
        var query = new GetPositionByIdQuery(positionId);
        var response = await _mediator.Send(query);
        return View(response);
    }
    
    [HttpGet]
    public async Task<IActionResult> Delete(int positionId)
    {
        var command = new DeletePositionCommand(positionId);
        await _mediator.Send(command);
        return RedirectToAction("Index");
    }
    
    [HttpGet]
    public async Task<IActionResult> Edit(int positionId)
    {
        var query = new GetPositionByIdQuery(positionId);
        var position = await _mediator.Send(query);
        return View(position);
    }
    
    [HttpPost]
    public async Task<IActionResult> Update(IFormCollection collection)
    {
        var positionId = int.Parse(collection["Id"]!);
        var departmentId = int.Parse(collection["departmentId"]!);
        var name = collection["Name"];
        var positionDto = new PositionDto(name!, departmentId);
        var command = new UpdatePositionCommand(positionDto, positionId);
        await _mediator.Send(command);
        return RedirectToAction("Index");
    }
}

HRM/HRM.MVC/Views/Position/Add.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model HRM.MVC.ViewModels.AddPositionViewModel

@{
    ViewBag.Title = "Add";
    Layout = "_Layout";
}

<h2>Form to add a new position</h2>
<div class="row">
    <div class="col-md-6">
        <form asp-action="Add" method="post">
            <div class="form_row">
                <label for="">
                    Name
                    <input asp-for="Name" type="text">
                </label>
                <span asp-validation-for="Name"></span>
            </div>
            <div class="form_row">
                <label asp-for="DepartmentName" ></label>
                <select asp-for="DepartmentName" asp-items="ViewBag.Departments"></select>
                <span asp-validation-for="DepartmentName"></span>
            </div>
            <button type="submit">Add</button>
        </form>
    </div>
</div>

HRM/HRM.MVC/Views/Position/Edit.cshtml
@model Domain.Entities.Position

@{
    ViewBag.Title = "Edit";
    Layout = "_Layout";
}

<h2>Form to edit position</h2>

@using (Html.BeginForm("Update", "Position", FormMethod.Post))
{
    <fieldset>
        <p><b>Associate Id : </b>@Model.Id</p>
        @Html.HiddenFor(m => m.Id)
        <p><b>Associate department Id : </b>@Model.DepartmentId</p>
        @Html.HiddenFor(m => m.DepartmentId)
        <p>
            @Html.LabelFor(m => m.Name, "Name")
            <br/>
            @Html.EditorFor(m => m.Name)
        </p>
        <p><input type="submit" value="Edit"/></p>
    </fieldset>
}

HRM/HRM.MVC/Views/Position/GetById.cshtml
@model Domain.Entities.Position

@{
    ViewBag.Title = "Position info";
    Layout = "_Layout";
}

<h1>@Model.Name</h1>

<div class="table_section">
    <table style="width: 100%;">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Department Id</th>
        </tr>
        <tr>
            <td>@Model.Id</td>
            <td>@Model.Name</td>
            <td>@Model.DepartmentId</td>
        </tr>
    </table>
</div>

HRM/HRM.MVC/Views/Position/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model List<Domain.Entities.Position>
@{
    ViewBag.Title = "Positions";
    Layout = "_Layout";
}

<h2>Company positions</h2>
<a asp-action="Add" asp-controller="Position">Add position</a>
<div class="table_section">
    @if (@Model.Count == 0)
    {
        <p>There is no any positions yet.</p>
    }
    else
    {
        <table style="width: 100%;">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Department</th>
            </tr>
            @foreach (var position in @Model)
            {
                <tr>
                    <td>@position.Id</td>
                    <td>@position.Name</td>
                    <td>@position.Department.Name</td>
                    <td>
                        <a asp-action="GetById" asp-controller="Position" asp-route-positionId="@position.Id">View</a>
                    </td>
                    <td>
                        <a asp-action="Delete" asp-controller="Position" asp-route-positionId="@position.Id">Delete</a>
                    </td>
                    <td>
                        <a asp-action="Edit" asp-controller="Position" asp-route-positionId="@position.Id">Edit</a>
                    </td>
                </tr>
            }
        </table>
    }
</div>